# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-05-06 09:01
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    replaces = [(b'forum', '0001_initial'), (b'forum', '0002_forum_restricted'), (b'forum', '0003_auto_20160904_1518'), (b'forum', '0004_thread_featured'), (b'forum', '0005_thread_banned_users')]

    dependencies = [
        ('sites', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        migrations.swappable_dependency(settings.COMMENTS_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('only_upgraders', models.BooleanField(default=False)),
                ('title', models.CharField(max_length=250)),
                ('slug', models.SlugField()),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Forum',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Title')),
                ('slug', models.SlugField(verbose_name='Slug')),
                ('description', models.TextField(verbose_name='Description')),
                ('ordering', models.IntegerField(blank=True, null=True, verbose_name='Ordering')),
                ('only_staff_posts', models.BooleanField(default=False)),
                ('only_staff_reads', models.BooleanField(default=False)),
                ('only_upgraders', models.BooleanField(default=False)),
                ('allowed_users', models.ManyToManyField(blank=True, help_text=b'Ignore if non-restricted', related_name='allowed_forums', to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='forum.Category')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child', to='forum.Forum')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sites.Site')),
            ],
            options={
                'ordering': ['ordering', 'title'],
                'verbose_name': 'Forum',
                'verbose_name_plural': 'Forums',
            },
        ),
        migrations.CreateModel(
            name='Thread',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Title')),
                ('slug', models.SlugField(max_length=105, verbose_name='Slug')),
                ('sticky', models.BooleanField(default=False, verbose_name='Sticky?')),
                ('closed', models.BooleanField(default=False, verbose_name='Closed?')),
                ('posts', models.IntegerField(default=0, verbose_name='Posts')),
                ('views', models.IntegerField(default=0, verbose_name='Views')),
                ('comment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='commentthread_set', to=settings.COMMENTS_MODEL)),
                ('forum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forum.Forum')),
                ('latest_post', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.COMMENTS_MODEL)),
                ('featured', models.BooleanField(default=False)),
                ('banned_users', models.ManyToManyField(blank=True, related_name='banned_forums', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-id',),
                'verbose_name': 'Thread',
                'verbose_name_plural': 'Threads',
            },
        ),
        migrations.AddField(
            model_name='forum',
            name='restricted',
            field=models.BooleanField(default=False),
        ),
    ]
