# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-09-04 15:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
from django.conf import settings


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0002_forum_restricted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thread',
            name='latest_post',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.COMMENTS_MODEL),
        ),
    ]
