# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-02-20 21:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0003_auto_20160904_1518'),
    ]

    operations = [
        migrations.AddField(
            model_name='thread',
            name='featured',
            field=models.BooleanField(default=False),
        ),
    ]
