# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-09-25 18:04
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('forum', '0004_thread_featured'),
    ]

    operations = [
        migrations.AddField(
            model_name='thread',
            name='banned_users',
            field=models.ManyToManyField(blank=True, related_name='banned_forums', to=settings.AUTH_USER_MODEL),
        ),
    ]
